export function getMockMentors() {
  return [
    {
      id: 1,
      name: "Alex Carter",
      subjects: ["Math", "Physics", "CS"],
      rating: 4.8,
      hourlyRate: 20,
      successRate: 0.9,
      aiScore: 0.86,
      availableNow: true,
      bio: "Explains concepts with real-world examples.",
      avatarUrl: "/placeholder.svg?height=80&width=80",
    },
    {
      id: 2,
      name: "Priya Shah",
      subjects: ["Chemistry", "Biology"],
      rating: 4.6,
      hourlyRate: 15,
      successRate: 0.82,
      aiScore: 0.78,
      availableNow: false,
      bio: "Patient mentor with step-by-step guidance.",
      avatarUrl: "/placeholder.svg?height=80&width=80",
    },
    {
      id: 3,
      name: "Marco Lin",
      subjects: ["Economics", "English", "History"],
      rating: 4.9,
      hourlyRate: 25,
      successRate: 0.93,
      aiScore: 0.88,
      availableNow: true,
      bio: "Focus on frameworks and exam strategies.",
      avatarUrl: "/placeholder.svg?height=80&width=80",
    },
    {
      id: 4,
      name: "Sara Gomez",
      subjects: ["CS", "Math"],
      rating: 4.7,
      hourlyRate: 0,
      successRate: 0.84,
      aiScore: 0.8,
      availableNow: true,
      bio: "Fast debugging and code walkthroughs.",
      avatarUrl: "/placeholder.svg?height=80&width=80",
    },
    {
      id: 5,
      name: "Kenji Ito",
      subjects: ["Physics"],
      rating: 4.4,
      hourlyRate: 10,
      successRate: 0.75,
      aiScore: 0.7,
      availableNow: false,
      bio: "Intuition-first explanations.",
      avatarUrl: "/placeholder.svg?height=80&width=80",
    },
    {
      id: 6,
      name: "Mina Park",
      subjects: ["Math", "Chemistry"],
      rating: 4.5,
      hourlyRate: 12,
      successRate: 0.8,
      aiScore: 0.72,
      availableNow: true,
      bio: "Practice problems and exam prep.",
      avatarUrl: "/placeholder.svg?height=80&width=80",
    },
  ]
}
